version: '3.8'
services:
    mysql57:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 9001:3306
    mysql80:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 9002:3306
    mariadb11:
        image: mariadb:11
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: test_db
            MARIADB_ROOT_PASSWORD: password
        ports:
            - 9003:3306
    postgresql10:
        image: postgres:10
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 9004:5432
    postgresql16:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 9005:5432
    sqlsrv2019:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: unless-stopped
        environment:
            ACCEPT_EULA: "y"
            MSSQL_PID: Developer
            MSSQL_SA_PASSWORD: P@ssword123
            SA_PASSWORD: P@ssword123
        ports:
            - 9007:1433
